name: eco_market
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  logger: ^2.0.2+1
  smooth_page_indicator: ^1.1.0
  iconsax_flutter: ^1.0.0
  http: ^1.1.2
  skeleton_text: ^3.0.1
  flutter_blurhash: ^0.8.2
  flutter_screenutil: ^5.9.0
  flutter_bloc: ^8.1.3
  cached_network_image: ^3.3.1
  equatable: ^2.0.5
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2
  auto_route: ^7.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: TTNormsPro
      fonts:
        - asset: assets/fonts/TTNormsPro-Bold.ttf
        - asset: assets/fonts/TTNormsPro-BoldItalic.ttf
        - asset: assets/fonts/TTNormsPro-ExtraBold.ttf
        - asset: assets/fonts/TTNormsPro-ExtraBoldItalic.ttf
        - asset: assets/fonts/TTNormsPro-ExtraLightItalic.ttf
        - asset: assets/fonts/TTNormsPro-Italic.ttf
        - asset: assets/fonts/TTNormsPro-Light.ttf
        - asset: assets/fonts/TTNormsPro-LightItalic.ttf
        - asset: assets/fonts/TTNormsPro-Medium.ttf
        - asset: assets/fonts/TTNormsPro-MediumItalic.ttf
        - asset: assets/fonts/TTNormsPro-Regular.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
